# Site
name: "Evil Dino"
title: "Evil Dino"
description: "Hacking, politics and art"
meta_description: "Nirmal Lanka's personal blog and website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-96481074-1'
disqus: 'evil-dinosaur'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
twitter: https://twitter.com/srdyel
owner: "Nirmal Lankathilaka"

# Authors
authors:
  nir:
    name: Lanka
    display_name: Lanka
    gravatar: 0abad243be4a7a44b062c57643c89e19
    email: nir@evildino.com
    web: https://evildino.com
    twitter: https://twitter.com/srdyel
    description: "Hacker, engineer, artist, writer, musician. Hates BitCoin."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jemoji
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

relative_permalinks: false